name: Verify NIDs
on: [push]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt install python3 python3-lxml
      - name: Verify NIDs
        run: |
          python3 ./verify-sources.py
